### ISSUE TITLE
The details of densepose uv image extraction

### ISSUE THREAD

**Issue by xuchao1688** [yumingj/Text2Human#6]
Could you provide the details of extaction of densepose image, e.g. which model or cfg you use? I try using densepose repo in detectron2, which the results are slightly different from yours. However, even for the same origin human image, my densepose image cannot generate segmentation and human, while yours can.

**Comment by xuchao1688** [comment]
<img width="1099" alt="wecom-temp-e08b4a51cda028db0c64bd3bf523d7b4" src="https://user-images.githubusercontent.com/14347499/172762454-749dc9dd-1137-44ad-92dc-29c3786943ee.png">
The difference is like this

**Comment by yumingj** [comment]
Hi, I the weights I used is "https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl" and I use infer_simple.py.

Our densepose is extracted using the original 750x1101 images and croppoed 512x1024 from the original images. But I think that couldn't be the reason.

Could you please kindly attached your extracted example densepose in google drive or as an attachment so that I can download it? I will have a try on your extracted densepose to see where the problem is. Thanks!

**Comment by xuchao1688** [comment]
Thanks for your quick ansower, the densepose repo I use is [https://github.com/facebookresearch/detectron2/tree/main/projects/DensePose](url). The config is `densepose_rcnn_R_101_FPN_DL_s1x.yaml` and pretrianed model url is [https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_DL_s1x/165712116/model_final_844d15.pkl](url)

**Comment by xuchao1688** [comment]
![WOMEN-Dresses-id_00000229-02_1_front_dp_uv](https://user-images.githubusercontent.com/14347499/172769794-15bf0fda-159a-4708-b1fa-418c3ef805e4.jpg)
This is the densepose image extracted by myself.

**Comment by yumingj** [comment]
I use this repo (https://github.com/facebookresearch/DensePose) to extract the densepose.
The config file is "configs/DensePose_ResNet101_FPN_s1x-e2e.yaml".

Actually, for the extracted densepose, we only use the instance map of the iuv map. I guess the format of your extracted densepose is different so that you cannot successfully synthesize human images.

**Comment by xuchao1688** [comment]
We create the densepose image by placing the uv uint8 coordinate to G and R channel, B set zeros, like the issue [https://github.com/facebookresearch/detectron2/issues/1053](url) mentioned

**Comment by xuchao1688** [comment]
i am not very sure about your saying `we only use the instance map of the iuv map.` Could you provide the modified script?

**Comment by yumingj** [comment]
The reason your densepose doesn't work is that you set one channel as zero.

[This](https://github.com/yumingj/Text2Human/blob/7627593501e1e8ddb774ceb8b51ad02d3984c2e3/data/parsing_generation_segm_attr_dataset.py#L42) is how way load the densepose. We only use the last channel of the extracted densepose.

**Comment by xuchao1688** [comment]
Thanks for your solution! You only use the i channel, however i set this to zero.

**Comment by yumingj** [comment]
Yes. That's the reason.

**Comment by etomasic** [comment]
@xuchao1688 how did you end up resolving this? When I don't set the last (i) channel to zero, it ends up producing weird results for the first step of parsing.

Did you just use the original DensePose instead of the detectron2 model? I am a bit wary of doing that since it uses python2 and other older versions that I already had some difficulties installing.

**Comment by xuchao1688** [comment]
@etomasic I still use the detectron2 model. Although its result is a bit different from the original one provided by author, the parsing generated is still acceptable. I set the IUV matrix to RGB channel as an normal image restored.

**Comment by etomasic** [comment]
![Screenshot 2022-06-27 141733](https://user-images.githubusercontent.com/45695696/176020056-d35e8962-a295-4d77-b6de-e6c289b8ddcd.png)

Is the image on the left similar at all to what you do? I used the code linked above ([this](https://stackoverflow.com/questions/62710513/is-there-a-way-to-obtain-iuv-map-from-image-in-tensorflow/68861456#68861456)), but without setting the i channel to 0.

**Comment by etomasic** [comment]
Never mind, I figured it out. I had to get rid of the multiplication by 255 when saving it as an image.
